version: '3'
services:
  peer1:
    build: .
    ports:
      - "5001:5001"  # Port pour la communication TCP
      - "8002:8002"  # Port pour la communication UDP (découverte)
    environment:
      - PEER_NAME=peer1
      - PEER_PORT=5001
      - UDP_PORT=8002
    networks:
      - p2p_network

  peer2:
    build: .
    ports:
      - "5002:5002"  # Port pour la communication TCP
      - "8003:8003"  # Port pour la communication UDP (découverte)
    environment:
      - PEER_NAME=peer2
      - PEER_PORT=5002
      - UDP_PORT=8003
    networks:
      - p2p_network

networks:
  p2p_network:
    driver: bridge
